### ISSUE TITLE
pip failed to install pygame-ai

### ISSUE THREAD

**Issue by Starcatcher2009** [nek2712/pygame-ai#1]
log:
```
Collecting pygame-ai
  Using cached pygame_ai-0.1.2-py3-none-any.whl (30 kB)
Collecting pygame<2 (from pygame-ai)
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...


      Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
        File "C:\Users\Dell Inspiron\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Dell Inspiron\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Dell Inspiron\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Dell Inspiron\AppData\Local\Temp\pip-build-env-eut0jne3\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Dell Inspiron\AppData\Local\Temp\pip-build-env-eut0jne3\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\Dell Inspiron\AppData\Local\Temp\pip-build-env-eut0jne3\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Dell Inspiron\AppData\Local\Temp\pip-build-env-eut0jne3\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 194, in <module>
        File "C:\Users\Dell Inspiron\AppData\Local\Temp\pip-install-oojwmda3\pygame_4d88bdb81a334b9fb58269a0a4c36943\buildconfig\config.py", line 210, in main
          deps = CFG.main(**kwds)
        File "C:\Users\Dell Inspiron\AppData\Local\Temp\pip-install-oojwmda3\pygame_4d88bdb81a334b9fb58269a0a4c36943\buildconfig\config_win.py", line 576, in main
          and download_win_prebuilt.ask(**download_kwargs):
        File "C:\Users\Dell Inspiron\AppData\Local\Temp\pip-install-oojwmda3\pygame_4d88bdb81a334b9fb58269a0a4c36943\buildconfig\download_win_prebuilt.py", line 302, in ask
          reply = raw_input(
      EOFError: EOF when reading a line
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by RFlintstone** [comment]
I have the same issue.

**Comment by frsfth25** [comment]
I have the same issue too
I used Python version 3.10.11 btw
Is this project discontinued?
